services:
  - type: web
    name: video-downloader
    runtime: python
    envVars:
      - key: PORT
        value: 10000
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    aptPackages:
      - ffmpeg
